### ISSUE TITLE
AWS KMS integrated

### ISSUE THREAD

**Issue by Roxyrob** [sumup-oss/terraform-provider-vaulted#33]
Hi,
not tested extensively, but it seems a good solution. I know a requirement was self-contained code, but why not using AWS KMS/CMK symmetric Encrypt/Decrypt ? That will be hiding Encryptin/Decrypton keys totally by developers, make painless keys management (no more spread of priv/pub keys) and probably simplify or avoid Rotating and Rekeing secrets as AWS KMS does not use directly master keys to Encrypt.

**Comment by syndbg** [comment]
Hey, sorry for the late reply, I'm really bad with notifications.

The motivation behind the usage of AWS KMS asymm was to enable self-service so that people without access to AWS KMS APIs can do that easily.

E.g practical (and real SumUp) scenario is having a public key in a repository where any developer from the company can encrypt a new secret, totally via self-service.  No need for extraneous access management, AWS CLI debugging, etc, etc, etc.
